import type { Dv2 } from "../../interface/Dv2/dv2-list-interface";

// import type { Dv2 } from "../../../interface/Dv2/dv2-list-interface";
// import { dv2Data } from "../../../utils/Dv2/demo-data"; 

export const dv2Data: Dv2[] = [
    {
      salesTerritory: "NM",
      main: "G2",
      sub: "P1",
      client: ["S-LSI"],
      category: "DPX",
      band: "B26",
      partName: "MXM26ATQ001A",
      chip: "HS",
      pkg: "CSP",      
      group: "선행",
      pl: null,
      operator: null,
      status: "DVR2",
      turn: "PS1M",
      dateOfMdr: "2025-02-13",
      dateOfFabIn: "",
      dateOfFabOut: "",
      dateOfHqOut: "",
      dateOfWhcIn: "",
      dateOfAssyIn: "",
      dateOfDCOut: "",
      dateOfMeasIn: "",
      dateOfEstimatedMdr : "2025-02-13",
      dateOfEstimatedFabIn: "2025-02-18",
      dateOfEstimatedFabOut: "2025-03-06",
      dateOfEstimatedHqOut: "2025-03-12",
      dateOfEstimatedWhcIn: "2025-03-14",
      dateOfEstimatedAssyIn: "2025-03-15",
      dateOfEstimatedDCOut: "2025-03-21",
      dateOfEstimatedMeasIn: "2025-03-22",
      dateOfEstimatedCer: "2025-03-28",
      dvrPriority: "3",
      currentStage : "",
      userOfSupporter : "",
      userOfDesigner : ""
    },
    {
      salesTerritory: "NM",
      main: "G2",
      sub: "P1",
      client: ["-"],
      category: "QPX",
      band: "B1+B3",
      partName: "MQM03AZ8001A",
      chip: "HS",
      pkg: "CSP",      
      group: "선행",
      pl: null,
      operator: null,
      status: "DVR2",
      turn: "PS2M",
      dateOfMdr: "2025-02-13",
      dateOfFabIn: "",
      dateOfFabOut: "",
      dateOfHqOut: "",
      dateOfWhcIn: "",
      dateOfAssyIn: "",
      dateOfDCOut: "",
      dateOfMeasIn: "",
      dateOfEstimatedMdr : "2025-02-13",
      dateOfEstimatedFabIn: "2025-02-18",
      dateOfEstimatedFabOut: "2025-03-06",
      dateOfEstimatedHqOut: "2025-03-12",
      dateOfEstimatedWhcIn: "2025-03-14",
      dateOfEstimatedAssyIn: "2025-03-15",
      dateOfEstimatedDCOut: "2025-03-21",
      dateOfEstimatedMeasIn: "2025-03-22",
      dateOfEstimatedCer: "2025-03-28",
      dvrPriority: "3",
      currentStage : "",
      userOfSupporter : "",
      userOfDesigner : ""
    },
    {
      salesTerritory: "NM",
      main: "G2",
      sub: "P1",
      client: ["-"],
      category: "DPX",
      band: "B5",
      partName: "MXM05ANR001A",
      chip: "TS",
      pkg: "CSP",      
      group: "상품A",
      pl: null,
      operator: null,
      status: "DVR2",
      turn: "PS1M",
      dateOfMdr: "2025-02-13",
      dateOfFabIn: "",
      dateOfFabOut: "",
      dateOfHqOut: "",
      dateOfWhcIn: "",
      dateOfAssyIn: "",
      dateOfDCOut: "",
      dateOfMeasIn: "",
      dateOfEstimatedMdr : "2025-02-13",
      dateOfEstimatedFabIn: "2025-02-21",
      dateOfEstimatedFabOut: "2025-03-10",
      dateOfEstimatedHqOut: "2025-03-14",
      dateOfEstimatedWhcIn: "2025-03-16",
      dateOfEstimatedAssyIn: "2025-03-17",
      dateOfEstimatedDCOut: "2025-03-21",
      dateOfEstimatedMeasIn: "2025-03-22",
      dateOfEstimatedCer: "2025-03-28",
      dvrPriority: "3",
      currentStage : "",
      userOfSupporter : "",
      userOfDesigner : ""
    },
    {
      salesTerritory: "NM",
      main: "G2",
      sub: "P1",
      client: ["S-LSI G"],
      category: "RX",
      band: "B5",
      partName: "MHM08AA4001A",
      chip: "TS",
      pkg: "CSP",      
      group: "상품A",
      pl: null,
      operator: null,
      status: "DVR2",
      turn: "PS1M",
      dateOfMdr: "2024-10-06",
      dateOfFabIn: "",
      dateOfFabOut: "",
      dateOfHqOut: "",
      dateOfWhcIn: "",
      dateOfAssyIn: "",
      dateOfDCOut: "",
      dateOfMeasIn: "",
      dateOfEstimatedMdr : "",
      dateOfEstimatedFabIn: "2025-02-10",
      dateOfEstimatedFabOut: "2025-02-24",
      dateOfEstimatedHqOut: "2025-02-28",
      dateOfEstimatedWhcIn: "2025-03-02",
      dateOfEstimatedAssyIn: "2025-03-03",
      dateOfEstimatedDCOut: "2025-03-07",
      dateOfEstimatedMeasIn: "2025-03-08",
      dateOfEstimatedCer: "2025-03-22",
      dvrPriority: "3",
      currentStage : "",
      userOfSupporter : "",
      userOfDesigner : ""
    },
    {
      salesTerritory: "NM",
      main: "G2",
      sub: "P1",
      client: ["S-LSI"],
      category: "RX",
      band: "B12/13/14/68/85",
      partName: "MH748AA40L1A",
      chip: "TS",
      pkg: "CSP",      
      group: "상품A",
      pl: null,
      operator: null,
      status: "DVR2",
      turn: "PS1M",
      dateOfMdr: "2024-07-09",
      dateOfFabIn: "",
      dateOfFabOut: "",
      dateOfHqOut: "",
      dateOfWhcIn: "",
      dateOfAssyIn: "",
      dateOfDCOut: "",
      dateOfMeasIn: "",
      dateOfEstimatedMdr : "",
      dateOfEstimatedFabIn: "2025-02-10",
      dateOfEstimatedFabOut: "2025-02-26",
      dateOfEstimatedHqOut: "2025-02-28",
      dateOfEstimatedWhcIn: "2025-03-02",
      dateOfEstimatedAssyIn: "2025-03-03",
      dateOfEstimatedDCOut: "2025-03-07",
      dateOfEstimatedMeasIn: "2025-03-08",
      dateOfEstimatedCer: "2025-03-22",
      dvrPriority: "3",
      currentStage : "",
      userOfSupporter : "",
      userOfDesigner : ""
    },
    {
      salesTerritory: "NM",
      main: "G2",
      sub: "P1",
      client: ["S-LSI,MTK"],
      category: "RX",
      band: "B71",
      partName: "MHM71BA4000A",
      chip: "TS",
      pkg: "CSP",      
      group: "상품A",
      pl: null,
      operator: null,
      status: "DVR2",
      turn: "PS0M",
      dateOfMdr: "2025-02-06",
      dateOfFabIn: "",
      dateOfFabOut: "",
      dateOfHqOut: "",
      dateOfWhcIn: "",
      dateOfAssyIn: "",
      dateOfDCOut: "",
      dateOfMeasIn: "",
      dateOfEstimatedMdr : "",
      dateOfEstimatedFabIn: "2025-02-12",
      dateOfEstimatedFabOut: "2025-02-26",
      dateOfEstimatedHqOut: "2025-03-04",
      dateOfEstimatedWhcIn: "2025-03-06",
      dateOfEstimatedAssyIn: "2025-03-07",
      dateOfEstimatedDCOut: "2025-03-13",
      dateOfEstimatedMeasIn: "2025-03-13",
      dateOfEstimatedCer: "2025-03-28",
      dvrPriority: "3",
      currentStage : "",
      userOfSupporter : "",
      userOfDesigner : ""
    },
    {
      salesTerritory: "NM",
      main: "G2",
      sub: "P1",
      client: ["S-LSI"],
      category: "DPX",
      band: "B7",
      partName: "XM07ATK@1M",
      chip: "HS",
      pkg: "CSP",      
      group: "선행",
      pl: null,
      operator: null,
      status: "DVR2",
      turn: "PS1M",
      dateOfMdr: "2024-11-21",
      dateOfFabIn: "",
      dateOfFabOut: "",
      dateOfHqOut: "",
      dateOfWhcIn: "",
      dateOfAssyIn: "",
      dateOfDCOut: "",
      dateOfMeasIn: "",
      dateOfEstimatedMdr : "",
      dateOfEstimatedFabIn: "2024-11-29",
      dateOfEstimatedFabOut: "2024-12-17",
      dateOfEstimatedHqOut: "2025-01-17",
      dateOfEstimatedWhcIn: "2025-01-18",
      dateOfEstimatedAssyIn: "2025-01-20",
      dateOfEstimatedDCOut: "2025-01-20",
      dateOfEstimatedMeasIn: "2025-02-05",
      dateOfEstimatedCer: "2025-03-28",
      dvrPriority: "3",
      currentStage : "",
      userOfSupporter : "",
      userOfDesigner : ""
    },
    {
      salesTerritory: "NM",
      main: "G2",
      sub: "P1",
      client: ["S-LSI"],
      category: "RX",
      band: "B7",
      partName: "HM07AA4@1MA",
      chip: "NS",
      pkg: "CSP",      
      group: "상품W",
      pl: null,
      operator: null,
      status: "DVR2",
      turn: "PS1M",
      dateOfMdr: "2024-11-21",
      dateOfFabIn: "",
      dateOfFabOut: "",
      dateOfHqOut: "",
      dateOfWhcIn: "",
      dateOfAssyIn: "",
      dateOfDCOut: "",
      dateOfMeasIn: "",
      dateOfEstimatedMdr : "",
      dateOfEstimatedFabIn: "2024-11-29",
      dateOfEstimatedFabOut: "2024-12-17",
      dateOfEstimatedHqOut: "2025-01-17",
      dateOfEstimatedWhcIn: "2025-01-18",
      dateOfEstimatedAssyIn: "2025-01-20",
      dateOfEstimatedDCOut: "2025-01-20",
      dateOfEstimatedMeasIn: "2025-02-05",
      dateOfEstimatedCer: "2025-03-28",
      dvrPriority: "3",
      currentStage : "",
      userOfSupporter : "",
      userOfDesigner : ""
    },
  ];
  