import type { MdrApplication } from "./Interface";

export const dummyMdrApplications: MdrApplication[] = [
  {
    id: 1,
    weekNumber: 47,
    productName: "X806AH2",
    category: "내제SAW",
    packageType: "CSP",
    waferType: "HS",
    band: "B28",
    size: "Large",
    moduleName: "WLP-BIz",
    designer: "양원주",
    designerId: "D001",
    requester: "Requester 1",
    requesterId: "R001",
    group: "상품개발1G(Ryan)",
    status: "created",
    psNumber: "PS1",
    ganttPlanDate: "",
    executionDate: "2024-08-19",
    dateOfCreated: "",
    result: "pass",
    note: "Note for Product 1",
  },
  {
    id: 2,
    weekNumber: 18,
    productName: "HG41BF8",
    category: "Discrete",
    packageType: "WLP",
    waferType: "HS",
    band: "B15",
    size: "Medium",
    moduleName: "A6W0",
    designer: "안지민",
    designerId: "D002",
    requester: "Requester 2",
    requesterId: "R002",
    group: "요소기술그룹",
    status: "created",
    psNumber: "PS2",
    ganttPlanDate: "",
    executionDate: "2024-10-23",
    dateOfCreated: "",
    result: "fail",
    note: "Note for Product 2",
  },
  {
    id: 3,
    weekNumber: 36,
    productName: "E312NV4",
    category: "SAW",
    packageType: "BGA",
    waferType: "HR",
    band: "B7",
    size: "Small",
    moduleName: "ZLT-200",
    designer: "김철수",
    designerId: "D003",
    requester: "Requester 3",
    requesterId: "R003",
    group: "RF Module 개발",
    status: "in-progress",
    psNumber: "PS3",
    ganttPlanDate: "",
    executionDate: "2024-09-01",
    dateOfCreated: "",
    result: "pending",
    note: "Note for Product 3",
  },
  {
    id: 4,
    weekNumber: 15,
    productName: "P610KH3",
    category: "내제SAW",
    packageType: "CSP",
    waferType: "HP",
    band: "B12",
    size: "Large",
    moduleName: "SRF-700",
    designer: "이영희",
    designerId: "D004",
    requester: "Requester 4",
    requesterId: "R004",
    group: "상품개발2G(Jane)",
    status: "completed",
    psNumber: "PS4",
    ganttPlanDate: "",
    executionDate: "2024-06-11",
    dateOfCreated: "",
    result: "pass",
    note: "Note for Product 4",
  },
  {
    id: 5,
    weekNumber: 22,
    productName: "H905JK7",
    category: "SAW",
    packageType: "QFN",
    waferType: "HS",
    band: "B5",
    size: "Medium",
    moduleName: "ALP-310",
    designer: "박민수",
    designerId: "D005",
    requester: "Requester 5",
    requesterId: "R005",
    group: "RF팀",
    status: "created",
    psNumber: "PS5",
    ganttPlanDate: "",
    executionDate: "2024-05-23",
    dateOfCreated: "",
    result: "fail",
    note: "Note for Product 5",
  },
  {
    id: 6,
    weekNumber: 30,
    productName: "F810JK9",
    category: "Filter",
    packageType: "WLP",
    waferType: "HS",
    band: "B18",
    size: "Large",
    moduleName: "HRM-XC",
    designer: "장희진",
    designerId: "D006",
    requester: "Requester 6",
    requesterId: "R006",
    group: "신제품개발",
    status: "completed",
    psNumber: "PS6",
    ganttPlanDate: "",
    executionDate: "2024-07-21",
    dateOfCreated: "",
    result: "pass",
    note: "Note for Product 6",
  },
  {
    id: 7,
    weekNumber: 12,
    productName: "J205NM2",
    category: "내제SAW",
    packageType: "BGA",
    waferType: "HR",
    band: "B40",
    size: "Small",
    moduleName: "XZL-900",
    designer: "홍길동",
    designerId: "D007",
    requester: "Requester 7",
    requesterId: "R007",
    group: "모듈개발팀",
    status: "in-progress",
    psNumber: "PS7",
    ganttPlanDate: "",
    executionDate: "2024-04-05",
    dateOfCreated: "",
    result: "pending",
    note: "Note for Product 7",
  },
  {
    id: 8,
    weekNumber: 25,
    productName: "N345QX2",
    category: "Discrete",
    packageType: "CSP",
    waferType: "HR",
    band: "B3",
    size: "Large",
    moduleName: "YZP-150",
    designer: "최지은",
    designerId: "D008",
    requester: "Requester 8",
    requesterId: "R008",
    group: "RF 개발팀",
    status: "created",
    psNumber: "PS8",
    ganttPlanDate: "",
    executionDate: "2024-06-28",
    dateOfCreated: "",
    result: "pass",
    note: "Note for Product 8",
  },
  {
    id: 9,
    weekNumber: 40,
    productName: "U870LP9",
    category: "SAW",
    packageType: "QFN",
    waferType: "HS",
    band: "B8",
    size: "Medium",
    moduleName: "RFZ-230",
    designer: "김민지",
    designerId: "D009",
    requester: "Requester 9",
    requesterId: "R009",
    group: "신규기술개발",
    status: "completed",
    psNumber: "PS9",
    ganttPlanDate: "",
    executionDate: "2024-10-05",
    dateOfCreated: "",
    result: "fail",
    note: "Note for Product 9",
  },
  {
    id: 10,
    weekNumber: 29,
    productName: "Q620HK4",
    category: "Filter",
    packageType: "WLP",
    waferType: "HS",
    band: "B20",
    size: "Small",
    moduleName: "XLK-450",
    designer: "이수빈",
    designerId: "D010",
    requester: "Requester 10",
    requesterId: "R010",
    group: "모듈설계팀",
    status: "in-progress",
    psNumber: "PS10",
    ganttPlanDate: "",
    executionDate: "2024-07-15",
    dateOfCreated: "",
    result: "pending",
    note: "Note for Product 10",
  },
];
