import { ref } from "vue";

export interface TableData {
  customer: string;
  category: string;
  testType: string;
  signal_type: string;
  signal_info: string;
  temperature: string;
  time: string;
  vswr: string;
  input_Power: string;
  pcl: string;
}

export const tableData = ref<TableData[]>([
  {
    customer: "K1",
    category: "공통",
    testType: "MaxFuse",
    signal_type: "LTE",
    signal_info: "QPSK, 5MHz, 12RB",
    temperature: "85℃",
    time: "2  (Min)",
    vswr: "1:1",
    input_Power: "32dBm",
    pcl: "3",
  },
  {
    customer: "K1",
    category: "공통",
    testType: "Lifetime",
    signal_type: "LTE",
    signal_info: "QPSK, 5MHz, 1RB",
    temperature: "85℃",
    time: "5,000  (Hours)",
    vswr: "1:1",
    input_Power: "32dBm",
    pcl: "2",
  },
  {
    customer: "K1",
    category: "공통",
    testType: "Lifetime",
    signal_type: "LTE",
    signal_info: "QPSK, 5MHz, 1RB",
    temperature: "85℃",
    time: "5,000  (Hours)",
    vswr: "1:1",
    input_Power: "29dBm",
    pcl: "3",
  },
  {
    customer: "K1",
    category: "공통",
    testType: "Lifetime",
    signal_type: "NR",
    signal_info: "QPSK, 5MHz, 1RB",
    temperature: "85℃",
    time: "5,000  (Hours)",
    vswr: "1:1",
    input_Power: "30.5dBm",
    pcl: "2",
  },
  {
    customer: "K1",
    category: "공통",
    testType: "Lifetime",
    signal_type: "NR",
    signal_info: "QPSK, 5MHz, 1RB",
    temperature: "85℃",
    time: "5,000  (Hours)",
    vswr: "1:1",
    input_Power: "27.5dBm",
    pcl: "3",
  },
  {
    customer: "K1",
    category: "공통",
    testType: "Lifetime",
    signal_type: "WiFi",
    signal_info: "CW or WLAN (Ex. IEEE802.11g)",
    temperature: "85℃",
    time: "5,000  (Hours)",
    vswr: "1:1",
    input_Power: "25dBm",
    pcl: "-",
  },
  {
    customer: "전장",
    category: "공통",
    testType: "Lifetime",
    signal_type: "LTE",
    signal_info: "QPSK, 5MHz, 1RB",
    temperature: "85℃",
    time: "5,000  (Hours)",
    vswr: "1:1",
    input_Power: "29dBm",
    pcl: "Grade3",
  },
  {
    customer: "전장",
    category: "공통",
    testType: "Lifetime",
    signal_type: "NR",
    signal_info: "CP-OFDM, 5MHz, 1RB",
    temperature: "105℃",
    time: "5,000  (Hours)",
    vswr: "1:1",
    input_Power: "29dBm",
    pcl: "Grade2",
  },
  {
    customer: "전장",
    category: "공통",
    testType: "Lifetime",
    signal_type: "NR",
    signal_info: "CP-OFDM, 5MHz, 1RB",
    temperature: "125℃",
    time: "5,000  (Hours)",
    vswr: "1:1",
    input_Power: "29dBm",
    pcl: "Grade1",
  },
  {
    customer: "중화",
    category: "공통",
    testType: "Lifetime",
    signal_type: "LTE",
    signal_info: "QPSK, 5MHz, 1RB",
    temperature: "55℃",
    time: "5,000  (Hours)",
    vswr: "1:1",
    input_Power: "33dBm",
    pcl: "2",
  },
  {
    customer: "중화",
    category: "공통",
    testType: "Lifetime",
    signal_type: "LTE",
    signal_info: "QPSK, 5MHz, 1RB",
    temperature: "55℃",
    time: "5,000  (Hours)",
    vswr: "1:1",
    input_Power: "31dBm",
    pcl: "3",
  },
  {
    customer: "중화",
    category: "공통",
    testType: "Lifetime",
    signal_type: "NR",
    signal_info: "CP-OFDM, 5MHz, 1RB",
    temperature: "55℃",
    time: "5,000  (Hours)",
    vswr: "1:1",
    input_Power: "31.5dBm",
    pcl: "2",
  },
  {
    customer: "중화",
    category: "공통",
    testType: "Lifetime",
    signal_type: "NR",
    signal_info: "CP-OFDM, 5MHz, 1RB",
    temperature: "55℃",
    time: "5,000  (Hours)",
    vswr: "1:1",
    input_Power: "29.5dBm",
    pcl:"3",
  },
  {
    customer: "중화",
    category: "공통",
    testType: "Lifetime",
    signal_type: "WiFi",
    signal_info: "CW or WLAN (Ex. IEEE802.11g)",
    temperature: "85℃",
    time: "5,000  (Hours)",
    vswr: "1:1",
    input_Power: "25dBm",
    pcl: "-",
  },
  {
    customer: "중화",
    category: "Level 1 [OPPO/VIVO]",
    testType: "MaxFuse",
    signal_type: "LTE/NR",
    signal_info: "QPSK/DFT-S-OFDM, 5MHz, 1RB",
    temperature: "60℃",
    time: "30 Sec Per Step",
    vswr: "1:1, 6:1",
    input_Power: "32dBm (1:1), 30dBm (6:1)",
    pcl: "3",
  },
  {
    customer: "중화",
    category: "Level 1 [OPPO/VIVO]",
    testType: "MaxFuse",
    signal_type: "LTE/NR",
    signal_info: "QPSK/DFT-S-OFDM, 5MHz, 1RB",
    temperature: "60℃",
    time: "30 Sec Per Step",
    vswr: "1:1, 6:1",
    input_Power: "34dBm (1:1), 32dBm (6:1)",
    pcl: "2",
  },
  {
    customer: "중화",
    category: "Level 1 [OPPO/VIVO]",
    testType: "Corner MaxFuse",
    signal_type: "NR",
    signal_info: "QPSK/DFT-S-OFDM, 5MHz, 1RB ※ start 27 dBm, 0.5 dBm step",
    temperature: "85℃",
    time: "2  (Min)",
    vswr: "1:1",
    input_Power: "31dBm",
    pcl: "3",
  },
  {
    customer: "중화",
    category: "Level 1 [OPPO/VIVO]",
    testType: "Corner MaxFuse",
    signal_type: "NR",
    signal_info: "QPSK/DFT-S-OFDM, 5MHz, 1RB ※ start 27 dBm, 0.5 dBm step",
    temperature: "85℃",
    time: "2  (Min)",
    vswr: "1:1",
    input_Power: "33dBm",
    pcl: "2",
  },
  {
    customer: "중화",
    category: "Level 2 [OPPO/VIVO 外 Brand]",
    testType: "MaxFuse",
    signal_type: "LTE/NR",
    signal_info: "QPSK/DFT-S-OFDM, 5MHz, 1RB",
    temperature: "60℃",
    time: "2  (Min)",
    vswr: "1:1",
    input_Power: "32dBm",
    pcl: "3",
  },
  {
    customer: "중화",
    category: "Level 2 [OPPO/VIVO 外 Brand]",
    testType: "MaxFuse",
    signal_type: "LTE/NR",
    signal_info: "QPSK/DFT-S-OFDM, 5MHz, 1RB",
    temperature: "60℃",
    time: "2  (Min)",
    vswr: "1:1",
    input_Power: "34dBm",
    pcl: "2",
  },
  {
    customer: "중화",
    category: "Level 2 [OPPO/VIVO 外 Brand]",
    testType: "Corner MaxFuse",
    signal_type: "NR",
    signal_info: "QPSK/DFT-S-OFDM, 5MHz, 1RB ※ start 27 dBm, 0.5 dBm step",
    temperature: "85℃",
    time: "2  (Min)",
    vswr: "1:1",
    input_Power: "31dBm",
    pcl: "3",
  },
  {
    customer: "중화",
    category: "Level 2 [OPPO/VIVO 外 Brand]",
    testType: "Corner MaxFuse",
    signal_type: "NR",
    signal_info: "QPSK/DFT-S-OFDM, 5MHz, 1RB ※ start 27 dBm, 0.5 dBm step",
    temperature: "85℃",
    time: "2  (Min)",
    vswr: "1:1",
    input_Power: "33dBm",
    pcl: "2",
  },
  {
    customer: "중화",
    category: "Level 3 [ODM]",
    testType: "MaxFuse",
    signal_type: "LTE/NR",
    signal_info: "QPSK/DFT-S-OFDM, 5MHz, 1RB",
    temperature: "60℃",
    time: "2  (Min)",
    vswr: "1:1",
    input_Power: "31dBm (1:1)",
    pcl: "3",
  },
  {
    customer: "중화",
    category: "Level 3 [ODM]",
    testType: "MaxFuse",
    signal_type: "LTE/NR",
    signal_info: "QPSK/DFT-S-OFDM, 5MHz, 1RB",
    temperature: "60℃",
    time: "2  (Min)",
    vswr: "1:1",
    input_Power: "33dBm (1:1)",
    pcl: "2",
  },
  {
    customer: "중화",
    category: "Level 3 [ODM]",
    testType: "Corner MaxFuse",
    signal_type: "NR",
    signal_info: "QPSK/DFT-S-OFDM, 5MHz, 1RB ※ start 27 dBm, 0.5 dBm step",
    temperature: "85℃",
    time: "2  (Min)",
    vswr: "1:1",
    input_Power: "30dBm",
    pcl: "3",
  },
  {
    customer: "중화",
    category: "Level 3 [ODM]",
    testType: "Corner MaxFuse",
    signal_type: "NR",
    signal_info: "QPSK/DFT-S-OFDM, 5MHz, 1RB ※ start 27 dBm, 0.5 dBm step",
    temperature: "85℃",
    time: "2  (Min)",
    vswr: "1:1",
    input_Power: "32dBm",
    pcl: "2",
  },
]);
