export interface FabData {
  idx: number;
  week: string;
  separation: string;
  fabGroup: string;
  band: string;
  productName: string;
  stepNumber: string;
  pl: string;
  spl: string;
  support: string | null;
  purpose: string;
  importance: string;
  fabIn: string;
  fabOut: string;
  material: string;
  maker: string;
  cut: string;
  thick: string;
  waferCount: string;
  runSheet: string | null;
  runSheetDown: string | null;
  readingInTurn: string | null;
  reticleReceivingDate: string | null;
  executeCheck: string;
  comment: string | null;
  note: string | null;
  hideCheck: string;
  developer: string | null;
  lotId: string;
  realFabIn: string | null;
  realFabOut: string | null;
  leadTime: string | null;
  completeCheck: string;
  goalRate: string | null;
  nowProcessPosition: string | null;
  stopTime: string | null;
  machineName: string | null;
  machineState: string | null;
  edc: string | null;
  processComment: string | null;
  processNote: string | null;
  processDoc: string | null;
  processDocDown: string | null;
  developerDoc: string | null;
  developerDocDown: string | null;
  subPlProductionCall: string | null;
  subPlDeveloperCheck: string;
  subPlLeadTime: string | null;
  endProductionCall: string | null;
  engEngCheck: string;
  engLeadTime: string | null;
  fabOutComplete: string;
  deleteFlag: string;
  resultRunSheet: string | null;
  informStatue: string;
  informStatueCheck: string;
  informStatueCheckTime: string | null;
  informCheckText: string | null;
  lastProcessEndTime: string | null;
  currentHoldingFlag: number;
  eqengHoldingTime: number;
  skillHoldingTime: number;
  manufacturerHoldingTime: number;
  hasLastProcess: number;
  currentSeq: number;
  leadTimeStartSeq: number;
  routerLastSeq: number;
  scheduleComment: string | null;
  splLeadTimeComment: string | null;
  schedulerRouterContent: string | null;
  etcHoldingTime: number;
  developerTime: number;
  waitTime: number;
  currentHistorySeq: number;
  fabCardId: number;
  fabCardCheck: boolean;
}
